announce: false
audio_rolls_path: audio/
card_path: images/cards/
database_path: dicebot
gif_critical: https://media.giphy.com/media/QeiMi6xK1csJiY36r4/giphy.gif
gif_fumble: https://media.giphy.com/media/xT9Igoo05UKCnnXGtq/giphy.gif
gif_lucky: https://media.giphy.com/media/xUPGcEDVIQQS6hBbSo/giphy.gif
voice_volume: 0.4
