announce: true
database_path: dicebot
audio_path: audio
voice_subpath: diceroll-voice
audio_current_voice: sasha
card_path: images/cards/
dice_default: 1D100
dice_improve: 1D10
gif_critical: ['https://media.giphy.com/media/QeiMi6xK1csJiY36r4/giphy.gif']
gif_fumble: ['https://media1.tenor.com/images/5ceef192b0565fc2e6a4a33c14a034f0/tenor.gif','https://media.giphy.com/media/uWTJeNXDWkjT83Eye1/giphy.gif']
gif_lucky: ['https://media.giphy.com/media/xUPGcEDVIQQS6hBbSo/giphy.gif']
voice_volume: 0.4