# Generated by Django 4.0.4 on 2022-05-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('discord_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=6000)),
                ('base_points', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('damage', models.CharField(blank=True, max_length=32)),
                ('hands', models.IntegerField(blank=True, null=True)),
                ('base_range', models.CharField(blank=True, max_length=32)),
                ('uses_per_rnd', models.IntegerField(blank=True, null=True)),
                ('magazine', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, max_length=32, null=True)),
                ('malfunction', models.IntegerField(blank=True, null=True)),
                ('common_in_era', models.CharField(blank=True, max_length=32)),
                ('skill_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_points', models.IntegerField(default=0)),
                ('occupation_points', models.IntegerField(default=0)),
                ('experience_points', models.IntegerField(default=0)),
                ('improve', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('skill_fk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigator_name', models.CharField(max_length=50, verbose_name='Investigator')),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('birthplace', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='STR')),
                ('intelligence', models.IntegerField(blank=True, null=True, verbose_name='INT')),
                ('appearance', models.IntegerField(blank=True, null=True, verbose_name='APP')),
                ('dexterity', models.IntegerField(blank=True, null=True, verbose_name='DEX')),
                ('education', models.IntegerField(blank=True, null=True, verbose_name='EDU')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='SIZ')),
                ('constitution', models.IntegerField(blank=True, null=True, verbose_name='CON')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='POW')),
                ('luck', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('magic', models.IntegerField(blank=True, null=True)),
                ('san', models.IntegerField(blank=True, null=True)),
                ('san_daystart', models.IntegerField(blank=True, null=True)),
                ('temporary_insanity', models.BooleanField(default=False)),
                ('indefinite_insanity', models.BooleanField(default=False)),
                ('dying_unconcious', models.BooleanField(default=False)),
                ('dying_majorwound', models.BooleanField(default=False)),
                ('characterskill_fk', models.ManyToManyField(blank=True, to='charactersheet.skill')),
                ('player_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.player')),
                ('weapon_fk', models.ManyToManyField(blank=True, to='charactersheet.weapon')),
            ],
        ),
    ]
