# Generated by Django 4.0.4 on 2022-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='characterskill_fk',
            field=models.ManyToManyField(blank=True, to='charactersheet.characterskill'),
        ),
    ]
