# Generated by Django 4.0.4 on 2022-06-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0002_alter_character_characterskill_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='base_points',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
