# Generated by Django 4.0.4 on 2022-06-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0003_alter_skill_base_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterskill',
            name='base_calc_points',
            field=models.IntegerField(default=0),
        ),
    ]
