# Generated by Django 4.0.4 on 2022-07-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0004_characterskill_base_calc_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetime', models.DateField()),
                ('discord_id', models.IntegerField(blank=True, null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('reply_msg_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.player')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetime', models.DateTimeField(auto_now_add=True)),
                ('argument', models.CharField(blank=True, max_length=50)),
                ('equation', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('stat', models.IntegerField(blank=True, null=True)),
                ('success', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('message_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.discordmessage')),
                ('player_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.player')),
            ],
        ),
        migrations.DeleteModel(
            name='RollHistory',
        ),
    ]
