# Generated by Django 4.0.4 on 2022-08-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0005_discordmessage_roll_delete_rollhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='messagetime',
            field=models.DateTimeField(),
        ),
    ]
