# Generated by Django 4.0.4 on 2022-08-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0006_alter_discordmessage_messagetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
