# Generated by Django 4.0.4 on 2022-08-07 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0007_alter_player_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterskill',
            name='base_calc_points',
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='skill_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charactersheet.skill'),
        ),
    ]
