# Generated by Django 4.0.4 on 2022-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0008_remove_characterskill_base_calc_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='content',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
