# Generated by Django 4.0.4 on 2022-08-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0009_alter_discordmessage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordmessage',
            old_name='user',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='player_fk',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='message_fk',
        ),
    ]
