# Generated by Django 4.0.4 on 2022-08-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0010_rename_user_discordmessage_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
