# Generated by Django 4.0.4 on 2022-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0011_player_discord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='argument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='equation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='success',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
