# Generated by Django 4.0.4 on 2022-08-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0012_alter_roll_argument_alter_roll_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='omit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roll',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
