# Generated by Django 4.0.4 on 2022-08-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0013_roll_omit_alter_roll_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('int_ext', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior'), ('INT/EXT', 'Interior/Exterior')], max_length=32)),
                ('description', models.CharField(max_length=2000)),
                ('connection', models.ManyToManyField(blank=True, to='charactersheet.location')),
            ],
        ),
    ]
