# Generated by Django 4.0.4 on 2022-08-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0017_discordchannel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordmessage',
            old_name='channel',
            new_name='discordchannel',
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='channel',
            new_name='discordchannel',
        ),
    ]
