# Generated by Django 4.0.4 on 2022-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0018_rename_channel_discordmessage_discordchannel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='messagetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
