# Generated by Django 4.0.4 on 2022-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0019_alter_discordmessage_messagetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='messagetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roll',
            name='messagetime',
            field=models.DateTimeField(),
        ),
    ]
