# Generated by Django 4.0.4 on 2022-08-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0020_alter_discordmessage_messagetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='discord_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
