# Generated by Django 4.0.4 on 2022-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0021_alter_discordmessage_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='channel_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='discord_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
