# Generated by Django 4.0.4 on 2022-08-18 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0022_alter_discordchannel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='experience_points',
            field=models.IntegerField(default=0, help_text='All points beyond Base, Personal and Occupation.'),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='occupation_points',
            field=models.IntegerField(default=0, help_text='Points distributed from chosen Occupation pool.'),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='personal_points',
            field=models.IntegerField(default=0, help_text='Points distributed from Personal pool.'),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.player'),
            preserve_default=False,
        ),
    ]
