# Generated by Django 4.0.4 on 2022-08-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0023_alter_characterskill_experience_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='characterskill_fk',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon_fk',
        ),
        migrations.AddField(
            model_name='characterskill',
            name='character_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.character'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CharacterWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('character_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charactersheet.character')),
                ('weapon_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charactersheet.weapon')),
            ],
        ),
    ]
