# Generated by Django 4.0.4 on 2022-08-23 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0025_alter_skill_base_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='player_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charactersheet.player'),
        ),
    ]
