# Generated by Django 4.0.4 on 2022-08-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0027_character_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill grouping.', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief explanation of the use of the group.', max_length=100)),
                ('skills', models.ManyToManyField(related_name='skills', to='charactersheet.skill')),
            ],
        ),
    ]
