# Generated by Django 4.0.4 on 2022-09-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0029_alter_skill_base_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterskill',
            name='name_override',
            field=models.CharField(blank=True, help_text='Overrides the original skill name for just this character. Useful for things like Arts and Crafts or Language.', max_length=32, null=True),
        ),
    ]
