# Generated by Django 4.0.4 on 2022-09-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0030_characterskill_name_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
