# Generated by Django 4.0.4 on 2022-09-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0031_alter_discordchannel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='investigator_alias',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Investigator Alias'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='investigator_name',
            field=models.CharField(max_length=50, verbose_name='Investigator Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Magic'),
        ),
        migrations.AlterField(
            model_name='character',
            name='san',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAN'),
        ),
        migrations.AlterField(
            model_name='character',
            name='san_daystart',
            field=models.IntegerField(blank=True, null=True, verbose_name='START'),
        ),
    ]
